server:
  port: 5666
spring:
  profiles:
    active: dev
  application:
    name: mysql
  resources:
    add-mappings: false
  #shardingsphere proxy的配置  与配置mysql一样
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3321/readwrite_splitting_db   #数据库名是配置文件中配置
    username: root
    password: root


#mybatis-plus的sql日志
logging:
  level:
    com.baomidou.mybatisplus: info
    # 或者更精确地定位到SQL打印
    your.mapper.package: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #输出日志到控制台

mp:
  database:
    tables:
      abc: abc1
      bcd: bcd1